// Demo data used when ANTHROPIC_API_KEY is not set
// Simulates a media strategy for a fictional challenger bank "Vault"

export const DEMO_DATA: Record<string, string> = {
  briefing: JSON.stringify({
    brand: "Vault",
    intro: "Vault is a digital challenger bank launching its first current account in the Netherlands, targeting urban professionals who are frustrated with legacy banks. The campaign aims to build brand awareness and drive account openings, with a focus on Amsterdam, Rotterdam and Utrecht.",
    business_goals: [
      { goal: "Acquire new current account holders", target: "44,000 new accounts", metric: "Cost per acquisition ≤ €45" },
      { goal: "Build brand awareness among target audience", target: "40% aided awareness", metric: "Brand tracker (Kantar)" },
      { goal: "Drive app downloads", target: "80,000 downloads", metric: "App store installs" },
    ],
    marketing_goals: [
      { kpi: "Cost per Acquisition (CPA)", target: "≤ €45" },
      { kpi: "New account holders", target: "44,000" },
      { kpi: "Aided brand awareness", target: "40%" },
      { kpi: "App downloads", target: "80,000" },
      { kpi: "Share of Voice (SOV)", target: "15%" },
    ],
    params: {
      budget: "€2,000,000",
      duration: "10 weeks (Q1 2026)",
      geo: "Amsterdam, Rotterdam, Utrecht",
      timing: "January – March 2026",
    },
  }),

  audience: JSON.stringify({
    total: {
      name: "Total Audience",
      age_range: "25–38",
      jobs: "Knowledge workers, freelancers, young professionals",
      income: "€35,000–€70,000 gross/year",
      education: "HBO / University",
      living_situation: "Renting in city centre or inner ring",
      lifestyle: "Urban, digitally native, values time efficiency",
      media_prime_time: "07:00–09:00 and 20:00–23:00",
      daily_media_hours: "4.8 hours",
      motivations: ["Low fees and transparent pricing", "Full control via mobile app", "Fast onboarding without paperwork"],
      pain_points: ["Hidden bank charges", "Slow customer service", "Outdated mobile apps"],
      platforms: ["Instagram", "YouTube", "Google Search", "Spotify", "LinkedIn"],
      values: "Autonomy, transparency, efficiency",
      purchase_trigger: "Visible fee savings + peer recommendation",
      size_estimate: "~280,000 people across the 3 cities",
      platform_presence: [
        { platform: "Instagram",      reach_index: 88, selectivity_index: 72, score_label: "●●●●○" },
        { platform: "YouTube",        reach_index: 82, selectivity_index: 58, score_label: "●●●●○" },
        { platform: "Google Search",  reach_index: 68, selectivity_index: 91, score_label: "●●●●●" },
        { platform: "TikTok",         reach_index: 60, selectivity_index: 38, score_label: "●●●○○" },
        { platform: "LinkedIn",       reach_index: 44, selectivity_index: 85, score_label: "●●●○○" },
      ],
    },
    personas: [
      {
        name: "Daan",
        age: "28",
        job: "UX Designer at a scale-up",
        income: "€48,000/year",
        education: "HBO Design",
        living_situation: "Renting with partner, Amsterdam-West",
        lifestyle: "Cycles to work, gym 3x/week, orders groceries via app",
        media_prime_time: "07:30–08:30 commute + 21:00–23:00",
        daily_media_hours: "5.2 hours",
        pain_points: ["Pays €8/month at ING for nothing", "App crashes during iDEAL payments", "No spending insights"],
        motivations: ["Save €90+/year on fees", "Clean app UX", "Instant spending notifications"],
        platforms: ["Instagram", "YouTube", "Spotify"],
        values: "Design quality, efficiency, sustainability",
        purchase_trigger: "Friend recommends it, tries demo in 2 minutes",
        platform_presence: [
          { platform: "Instagram",     reach_index: 92, selectivity_index: 70, score_label: "●●●●●" },
          { platform: "YouTube",       reach_index: 85, selectivity_index: 55, score_label: "●●●●○" },
          { platform: "Google Search", reach_index: 60, selectivity_index: 88, score_label: "●●●●○" },
          { platform: "TikTok",        reach_index: 70, selectivity_index: 35, score_label: "●●●○○" },
          { platform: "LinkedIn",      reach_index: 35, selectivity_index: 80, score_label: "●●○○○" },
        ],
      },
      {
        name: "Sven",
        age: "33",
        job: "Freelance copywriter",
        income: "€55,000/year (variable)",
        education: "University — Dutch Literature",
        living_situation: "Own apartment, Rotterdam Centrum",
        lifestyle: "Works from cafés, travels 6x/year, side projects",
        media_prime_time: "09:00–11:00 and 22:00–23:30",
        daily_media_hours: "4.4 hours",
        pain_points: ["Separate accounts for business/personal is a hassle", "Bank doesn't understand freelancers", "Late invoice payments cause cash flow stress"],
        motivations: ["Instant payment notifications", "Easy expense categorisation", "No monthly fees eating into margin"],
        platforms: ["LinkedIn", "Instagram", "Google Search"],
        values: "Independence, financial control, professional credibility",
        purchase_trigger: "Sees competitor ad, searches for comparison, Vault ranks #1",
        platform_presence: [
          { platform: "Instagram",     reach_index: 75, selectivity_index: 68, score_label: "●●●●○" },
          { platform: "YouTube",       reach_index: 65, selectivity_index: 50, score_label: "●●●○○" },
          { platform: "Google Search", reach_index: 80, selectivity_index: 94, score_label: "●●●●●" },
          { platform: "TikTok",        reach_index: 30, selectivity_index: 25, score_label: "●●○○○" },
          { platform: "LinkedIn",      reach_index: 72, selectivity_index: 88, score_label: "●●●●○" },
        ],
      },
      {
        name: "Lisa",
        age: "26",
        job: "Junior consultant at Big4",
        income: "€42,000/year",
        education: "University — Business Economics",
        living_situation: "Shared apartment, Utrecht",
        lifestyle: "High achiever, works long hours, brand conscious",
        media_prime_time: "06:30–08:00 commute + 20:00–22:00",
        daily_media_hours: "3.8 hours",
        pain_points: ["Student debt repayment is stressful", "No savings insights from current bank", "Customer service takes too long"],
        motivations: ["Smart savings goals", "Cashback on purchases", "Looks good to peers"],
        platforms: ["TikTok", "Instagram", "YouTube"],
        values: "Ambition, status, financial security",
        purchase_trigger: "TikTok unboxing / review video from a creator she follows",
        platform_presence: [
          { platform: "Instagram",     reach_index: 95, selectivity_index: 78, score_label: "●●●●●" },
          { platform: "YouTube",       reach_index: 88, selectivity_index: 62, score_label: "●●●●○" },
          { platform: "Google Search", reach_index: 55, selectivity_index: 85, score_label: "●●●●○" },
          { platform: "TikTok",        reach_index: 90, selectivity_index: 48, score_label: "●●●●○" },
          { platform: "LinkedIn",      reach_index: 28, selectivity_index: 75, score_label: "●●○○○" },
        ],
      },
    ],
    barriers: [
      { barrier: "Switching banks feels like a lot of work", solution: "Emphasise 5-minute onboarding and automatic redirect service" },
      { barrier: "Trust — is a new bank safe?", solution: "Lead with DNB licence, deposit guarantee scheme (€100K), and security credentials" },
      { barrier: "Not sure it's worth it for the savings", solution: "Show concrete euro amount saved per year in all ads (personalised calculator)" },
    ],
  }),

  competitive: JSON.stringify({
    competitors: [
      {
        name: "Bunq",
        est_budget: "€3.5M/year estimated",
        channels: ["Meta", "YouTube", "OOH Amsterdam", "Influencer"],
        positioning: "The bank for independent thinkers — sustainability angle",
        strengths: ["Strong brand recognition among under-35s", "Sustainability positioning resonates", "High social following"],
        weaknesses: ["Premium pricing (€10.99/month)", "Perceived as expensive vs free alternatives", "Customer service complaints"],
        sov_pct: 28,
        market_share_pct: 22,
        recent_ads: [
          { format: "Video 30s", platform: "YouTube", description: "Brand film showing a freelancer managing multiple income streams with zero stress", angle: "Freedom & independence" },
          { format: "Stories", platform: "Instagram", description: "Carousel comparing Bunq's tree-planting feature vs traditional banks", angle: "Sustainability guilt-trip" },
        ],
      },
      {
        name: "Revolut",
        est_budget: "€5M/year estimated",
        channels: ["Meta", "Google Search", "App Store", "Affiliate"],
        positioning: "Global financial super-app — do everything in one place",
        strengths: ["Massive brand recognition", "Product breadth (crypto, stocks, travel)", "Aggressive referral programme"],
        weaknesses: ["Perceived as fintech toy, not a real bank", "No Dutch IBAN (UK-based)", "Customer service horror stories"],
        sov_pct: 35,
        market_share_pct: 18,
        recent_ads: [
          { format: "Search", platform: "Google", description: "Keyword targeting on 'goedkope bankrekening' and 'gratis bankrekening'", angle: "Performance / price comparison" },
          { format: "Video 15s", platform: "YouTube", description: "Quick demo of currency exchange with zero fees while travelling", angle: "Travel use case" },
        ],
      },
      {
        name: "N26",
        est_budget: "€2M/year estimated",
        channels: ["Meta", "YouTube", "Google Search"],
        positioning: "The mobile bank you'll actually love — simplicity first",
        strengths: ["Clean design aesthetic", "Strong consideration among design-conscious users", "Good NPS scores"],
        weaknesses: ["Less feature-rich than Revolut", "No Dutch customer support", "Recent layoffs hurt brand perception"],
        sov_pct: 18,
        market_share_pct: 12,
        recent_ads: [
          { format: "Feed", platform: "Instagram", description: "Minimalist product shots of the metal card with lifestyle backgrounds", angle: "Premium simplicity" },
          { format: "Video 20s", platform: "YouTube", description: "Side-by-side comparison of N26 vs legacy bank app speed", angle: "Speed & simplicity" },
        ],
      },
      {
        name: "ING / Rabobank (incumbents)",
        est_budget: "€40M+/year estimated",
        channels: ["TV", "OOH", "Radio", "Search", "Display"],
        positioning: "Trusted, established, local — the safe choice",
        strengths: ["Massive brand trust", "Full-service offering", "Physical branch network"],
        weaknesses: ["Old-fashioned UX", "Slow to innovate", "Monthly fees with little value"],
        sov_pct: 19,
        market_share_pct: 48,
        recent_ads: [
          { format: "TV 30s", platform: "TV / YouTube", description: "Family moments, trusted bank since 1881, emotional brand film", angle: "Heritage & trust" },
          { format: "Display", platform: "Programmatic", description: "Retargeting banner with mortgage rate comparison", angle: "Product push" },
        ],
      },
    ],
    sov: [
      { brand: "Revolut", pct: 35 },
      { brand: "Bunq", pct: 28 },
      { brand: "Incumbents", pct: 19 },
      { brand: "N26", pct: 18 },
    ],
    market_share: [
      { brand: "Incumbents", pct: 48 },
      { brand: "Bunq", pct: 22 },
      { brand: "Revolut", pct: 18 },
      { brand: "N26", pct: 12 },
    ],
    market_gaps: [
      { title: "No challenger owns the 'freelancer' positioning", description: "Bunq goes broad, Revolut focuses on travellers. The freelancer/ZZP segment (1.2M in NL) has no dedicated champion." },
      { title: "Trust gap at the bottom of the funnel", description: "Competitors focus on acquisition but few invest in reassurance content about safety and deposit guarantees." },
      { title: "Dutch-language social content is scarce", description: "Most challengers run English-language ads in NL. Dutch-language creative outperforms by 23% on recall (Nielsen 2024)." },
    ],
  }),

  funnel: JSON.stringify({
    stages: [
      {
        name: "Awareness",
        goal: "Reach 70% of target audience at least 3 times",
        channels: ["YouTube Pre-roll", "Meta Video", "Spotify Audio", "Programmatic Display"],
        kpi: "Impressions / Aided Awareness",
        target: "42M impressions · 40% awareness",
        message_type: "Emotional brand story — 'Banking that actually works for you'",
        budget_pct: 40,
        conversion_rate: "4.2% click-through to consideration",
      },
      {
        name: "Consideration",
        goal: "Drive active product comparison and app store visits",
        channels: ["Google Search", "Meta Carousel", "YouTube TrueView", "Reddit"],
        kpi: "Website visits / App store page views",
        target: "180,000 website visits · 95,000 app page views",
        message_type: "Rational comparison — fee savings calculator, feature checklist",
        budget_pct: 30,
        conversion_rate: "28% conversion from visit to app download",
      },
      {
        name: "Conversion",
        goal: "Drive account sign-ups at ≤ €45 CPA",
        channels: ["Google Search (brand)", "Meta Retargeting", "App Store Ads"],
        kpi: "Account openings / CPA",
        target: "44,000 accounts · CPA ≤ €45",
        message_type: "Urgency + social proof — 'Join 44,000 people who switched this month'",
        budget_pct: 22,
        conversion_rate: "46% complete onboarding after download",
      },
      {
        name: "Retention",
        goal: "Activate accounts and drive first transaction within 7 days",
        channels: ["Push notifications", "Email", "In-app messages"],
        kpi: "Activation rate / 30-day retention",
        target: "75% activation · 60% 30-day retention",
        message_type: "Onboarding tips + first transaction incentive (€5 cashback)",
        budget_pct: 8,
        conversion_rate: "",
      },
    ],
    retargeting: [
      "Website visitors who did not download the app → Meta + Google Display with fee-saving message (7-day window)",
      "App downloaders who did not complete sign-up → Push notification series + Meta retargeting (3-day window)",
      "Completed sign-up but no first transaction → Email + in-app nudge with €5 cashback offer (7-day window)",
    ],
    budget_split: [
      { stage: "Awareness", pct: 40 },
      { stage: "Consideration", pct: 30 },
      { stage: "Conversion", pct: 22 },
      { stage: "Retention", pct: 8 },
    ],
  }),

  channel: JSON.stringify({
    channels: [
      { name: "YouTube Pre-roll", role: "awareness", motivation: "Highest video reach among 25–38 urban professionals. Non-skippable 15s builds rapid brand familiarity at competitive CPM.", targeting: "25–38, Amsterdam/Rotterdam/Utrecht, interest: fintech, personal finance, design", formats: ["Non-skippable 15s", "Bumper 6s"], always_on: false, reach_index: 88, selectivity_index: 60, score_label: "●●●●○" },
      { name: "Meta Social", role: "awareness", motivation: "Unmatched targeting precision for urban professionals. Instagram Stories and Reels drive strong brand recall and click-through.", targeting: "25–38, 3 cities, behaviours: mobile banking app users, lookalike of current customer base", formats: ["Reels 15s", "Stories", "Feed carousel"], always_on: true, reach_index: 85, selectivity_index: 78, score_label: "●●●●●" },
      { name: "Google Search", role: "conversion", motivation: "Captures high-intent users actively searching for banking alternatives. Brand + competitor keywords drive lowest CPA in the mix.", targeting: "Keywords: gratis bankrekening, beste challenger bank, Bunq alternatief, Vault bank", formats: ["Responsive Search Ads", "Brand keywords"], always_on: true, reach_index: 52, selectivity_index: 94, score_label: "●●●●●" },
      { name: "Programmatic Display", role: "consideration", motivation: "Cost-efficient retargeting layer. Keeps Vault top-of-mind for users who engaged with video but haven't converted.", targeting: "Retargeting: video viewers + website visitors (30-day window). Contextual: personal finance content", formats: ["300x250", "728x90", "Native"], always_on: false, reach_index: 70, selectivity_index: 65, score_label: "●●●●○" },
      { name: "Spotify Audio", role: "awareness", motivation: "Reaches the audience during commute and gym — key moments when they're not scrolling. Audio + display combo drives 18% higher recall.", targeting: "25–35, urban, playlists: workout, commute, focus work", formats: ["Audio 30s + companion banner"], always_on: false, reach_index: 62, selectivity_index: 55, score_label: "●●●○○" },
      { name: "LinkedIn", role: "consideration", motivation: "Targets the freelancer/ZZP segment with precision. Sponsored InMail for freelancer-specific messaging about expense management.", targeting: "Freelancers, self-employed, 26–40, NL, job function: creative, consulting, tech", formats: ["Sponsored content", "InMail"], always_on: false, reach_index: 40, selectivity_index: 88, score_label: "●●●○○" },
    ],
    channel_overlap: [
      { channels: ["YouTube", "Meta"], overlap_pct: 44, insight: "44% of the target audience is reachable on both platforms. Coordinate creative to build a coherent brand story across both touchpoints." },
      { channels: ["YouTube", "Meta", "Search"], overlap_pct: 31, insight: "31% see all three — these are your highest-intent prospects. Ensure message progression from awareness → consideration → conversion." },
    ],
    attribution_model: "Data-driven attribution (Google) + Meta 7-day click / 1-day view",
    frequency_cap: "YouTube: 3x/week · Meta: 4x/week · Display: 5x/week",
    synergy_score: 82,
    synergy_notes: "Strong synergy between YouTube brand building and Google Search conversion. Users exposed to YouTube pre-roll show 2.3x higher Search CTR (Nielsen study, comparable fintech launch 2024).",
  }),

  budget: JSON.stringify({
    total_budget: 2000000,
    net_budget: 1800000,
    by_channel: [
      { channel: "Meta Social",           budget: 504000, pct: 28, motivation: "Highest ROI channel — precision targeting + always-on conversion" },
      { channel: "YouTube Pre-roll",      budget: 396000, pct: 22, motivation: "Primary awareness driver, strong brand recall" },
      { channel: "Google Search",         budget: 360000, pct: 20, motivation: "Lowest CPA channel — captures high intent" },
      { channel: "Programmatic Display",  budget: 252000, pct: 14, motivation: "Cost-efficient retargeting layer" },
      { channel: "Spotify Audio",         budget: 162000, pct: 9,  motivation: "Commute reach, incremental to video" },
      { channel: "LinkedIn",              budget: 126000, pct: 7,  motivation: "ZZP/freelancer segment precision" },
    ],
    by_funnel: [
      { stage: "Awareness",     budget: 720000, pct: 40 },
      { stage: "Consideration", budget: 540000, pct: 30 },
      { stage: "Conversion",    budget: 396000, pct: 22 },
      { stage: "Retention",     budget: 144000, pct: 8  },
    ],
    test_budget: {
      amount: 180000,
      pct: 10,
      tests: ["Dutch vs English creative A/B test", "Fee calculator vs emotional spot", "Influencer micro vs macro test"],
    },
    pacing: {
      strategy: "Burst + Always-on",
      motivation: "Heavy burst in weeks 1–3 to build rapid awareness, transition to always-on performance focus from week 4",
      weeks: [
        { week: 1,  budget: 280000, phase: "Burst",     focus: "Maximum launch reach. YouTube + Meta at full spend. All creatives live simultaneously to build instant brand presence." },
        { week: 2,  budget: 260000, phase: "Burst",     focus: "Sustain burst. Increase frequency for brand recall. Monitor CPM and pause underperforming ad sets." },
        { week: 3,  budget: 220000, phase: "Burst",     focus: "Wind down burst. Activate Google Search and LinkedIn. First conversion data starting to come in." },
        { week: 4,  budget: 180000, phase: "Peak",      focus: "Shift to performance mode. Retargeting activated. A/B test results analysed — scale winners." },
        { week: 5,  budget: 175000, phase: "Peak",      focus: "Optimise toward CPA ≤ €45. Double down on best-performing Meta audiences. Pause Spotify if CPM too high." },
        { week: 6,  budget: 155000, phase: "Peak",      focus: "Mid-campaign review. Reallocate budget from Display to Search if conversion rates hold." },
        { week: 7,  budget: 130000, phase: "Always-on", focus: "Steady state. Meta + Search as core always-on channels. Creative refresh to avoid fatigue." },
        { week: 8,  budget: 120000, phase: "Always-on", focus: "Retargeting intensification. CPA optimisation. Lookalike expansion based on converters." },
        { week: 9,  budget: 115000, phase: "Always-on", focus: "Long-tail conversions. Push referral programme to existing customers for organic growth." },
        { week: 10, budget: 95000,  phase: "Always-on", focus: "Final push. Maximise best performers. Prepare learnings document for Q2 planning." },
      ],
    },
  }),

  mediaplan: JSON.stringify({
    channels: [
      { name: "Meta Social", funnel_stage: "Awareness + Conversion", platform: "Meta (Facebook/Instagram)", buy_type: "Auction", targeting: "25–38, 3 cities, lookalike + interest", formats: ["Reels 15s", "Stories", "Feed"], budget: 504000, impressions: 28000000, reach: 220000, frequency: 3.8, cpm: 18.00, vtr: 42, cpv: 0.043, clicks: 840000, ctr: 3.0, cpc: 0.60, visits: 672000, cpa_visit: 0.75, conversions: 18144, cvr: 2.7, cpa: 27.78 },
      { name: "YouTube Pre-roll", funnel_stage: "Awareness", platform: "YouTube", buy_type: "Programmatic / Reserve", targeting: "25–38 urban, interest: fintech, personal finance", formats: ["Non-skippable 15s", "Bumper 6s"], budget: 396000, impressions: 22000000, reach: 185000, frequency: 3.2, cpm: 18.00, vtr: 36, cpv: 0.050, clicks: 440000, ctr: 2.0, cpc: 0.90, visits: 352000, cpa_visit: 1.13, conversions: 7040, cvr: 2.0, cpa: 56.25 },
      { name: "Google Search", funnel_stage: "Conversion", platform: "Google Ads", buy_type: "CPC auction", targeting: "Keywords: gratis bankrekening, challenger bank NL, Vault bank", formats: ["Responsive Search Ads"], budget: 360000, impressions: 3600000, reach: 120000, frequency: 2.1, cpm: 100.00, vtr: 0, cpv: 0, clicks: 288000, ctr: 8.0, cpc: 1.25, visits: 259200, cpa_visit: 1.39, conversions: 12960, cvr: 5.0, cpa: 27.78 },
      { name: "Programmatic Display", funnel_stage: "Consideration", platform: "DV360 / Trade Desk", buy_type: "Programmatic RTB", targeting: "Retargeting: video viewers + site visitors (30-day)", formats: ["300x250", "Native"], budget: 252000, impressions: 18000000, reach: 95000, frequency: 5.3, cpm: 14.00, vtr: 0, cpv: 0, clicks: 162000, ctr: 0.9, cpc: 1.56, visits: 129600, cpa_visit: 1.94, conversions: 2592, cvr: 2.0, cpa: 97.22 },
      { name: "Spotify Audio", funnel_stage: "Awareness", platform: "Spotify", buy_type: "Reservation", targeting: "25–35 urban, commute + workout playlists", formats: ["Audio 30s + companion banner"], budget: 162000, impressions: 5400000, reach: 72000, frequency: 2.5, cpm: 30.00, vtr: 0, cpv: 0, clicks: 54000, ctr: 1.0, cpc: 3.00, visits: 43200, cpa_visit: 3.75, conversions: 864, cvr: 2.0, cpa: 187.50 },
      { name: "LinkedIn", funnel_stage: "Consideration", platform: "LinkedIn", buy_type: "Auction", targeting: "Freelancers, ZZP, 26–40, NL", formats: ["Sponsored content", "InMail"], budget: 126000, impressions: 2100000, reach: 42000, frequency: 2.0, cpm: 60.00, vtr: 0, cpv: 0, clicks: 63000, ctr: 3.0, cpc: 2.00, visits: 50400, cpa_visit: 2.50, conversions: 2016, cvr: 4.0, cpa: 62.50 },
    ],
    totals: {
      budget: 1800000,
      impressions: 79100000,
      clicks: 1847000,
      conversions: 43616,
    },
  }),

  synthesis: JSON.stringify({
    summary: "Vault's Q1 2026 launch campaign positions the brand as the go-to digital bank for urban professionals aged 25–38 in Amsterdam, Rotterdam and Utrecht. With a €2M budget across 10 weeks, the strategy delivers an estimated 43,600 account openings at an average CPA of €41 — within the €45 target. The plan leads with a heavy awareness burst on YouTube and Meta, transitions to a performance-led always-on phase, and closes with retargeting and referral activation. Three personas — Daan, Sven and Lisa — anchor all creative decisions, ensuring relevance across design-conscious professionals, freelancers and career starters.",
    strategic_core: [
      "Own the 'zero-fee, full-control' positioning — no competitor has claimed this clearly in Dutch-language creative",
      "Lead with emotion, close with reason — brand film drives awareness, fee calculator closes conversion",
      "Meta + Search as the performance engine — these two channels deliver 70% of conversions at the lowest CPA",
    ],
    recommendations: [
      { title: "Produce Dutch-language creative from day one", description: "Research shows Dutch-language ads outperform English by 23% on recall among this target group. All hero assets should be in Dutch, even if the product UI is bilingual.", priority: "high" },
      { title: "Launch a referral programme in week 6", description: "At ~20,000 accounts opened by week 6, a referral mechanic (€10 for referrer + referee) can drive significant organic growth at €20 CPA — well below paid channels.", priority: "high" },
      { title: "Invest in a fee-savings calculator landing page", description: "Users converting from Search show 2.1x higher intent when they can input their current bank and see a personalised savings amount. Build this before launch.", priority: "medium" },
    ],
    risks: [
      { risk: "Bunq or Revolut respond with aggressive counter-spend", mitigation: "Monitor SOV weekly via Kantar. Have a contingency budget of €100K ready to defend Search keywords and key Meta audiences." },
      { risk: "CPA exceeds €45 in weeks 1–3 (burst phase)", mitigation: "Burst is intentionally brand-focused — CPA will be high early. Do not optimise toward CPA until week 4. Set a blended CPA target across the full 10 weeks." },
    ],
    next_steps: [
      { action: "Brief creative agency on hero brand film (30s) and social cutdowns (15s, 6s)", owner: "Brand team", timing: "Week –4 before launch" },
      { action: "Build fee-savings calculator and dedicated landing page", owner: "Product + Web team", timing: "Week –3 before launch" },
      { action: "Set up campaign tracking: UTM structure, Adjust/Appsflyer, Google Analytics 4", owner: "Data & Analytics", timing: "Week –2 before launch" },
    ],
  }),
};
