// Demo data used when ANTHROPIC_API_KEY is not set
// Simulates a media strategy for a fictional challenger bank "Vault"

export const DEMO_DATA: Record<string, string> = {
  briefing: JSON.stringify({
    brand: "Vault",
    intro: "Vault is a digital challenger bank launching its first current account in the Netherlands, targeting urban professionals who are frustrated with legacy banks. The campaign aims to build brand awareness and drive account openings, with a focus on Amsterdam, Rotterdam and Utrecht.",
    business_goals: [
      { goal: "Acquire new current account holders", target: "44,000 new accounts", metric: "Cost per acquisition ≤ €45" },
      { goal: "Build brand awareness among target audience", target: "40% aided awareness", metric: "Brand tracker (Kantar)" },
      { goal: "Drive app downloads", target: "80,000 downloads", metric: "App store installs" },
    ],
    marketing_goals: [
      { kpi: "Cost per Acquisition (CPA)", target: "≤ €45" },
      { kpi: "New account holders", target: "44,000" },
      { kpi: "Aided brand awareness", target: "40%" },
      { kpi: "App downloads", target: "80,000" },
      { kpi: "Share of Voice (SOV)", target: "15%" },
    ],
    params: {
      budget: "€2,000,000",
      duration: "10 weeks (Q1 2026)",
      geo: "Amsterdam, Rotterdam, Utrecht",
      timing: "January – March 2026",
    },
  }),


  market: JSON.stringify({
    tam:           "€2.4B",
    sam:           "€380M",
    target_size:   "~280,000 users",
    growth:        "+18% YoY",
    segments: [
      { name: "Urban professionals", pct: 42 },
      { name: "Freelancers / ZZP",   pct: 31 },
      { name: "Students / starters", pct: 27 },
    ],
    trends: [
      { direction: "up",   title: "Mobile-first banking growth",      description: "+34% app-only account openings YoY in NL (DNB, 2024)" },
      { direction: "up",   title: "Rising fee sensitivity",            description: "62% of switchers cite fees as primary trigger (DNB Consumer Survey 2024)" },
      { direction: "down", title: "Declining trust in incumbents",     description: "NPS for big-4 banks dropped 12 pts over 2 years (Bain 2024)" },
    ],
    consumer_behaviour: "Consumers increasingly expect banking apps to perform like modern consumer tech: instant, transparent and frictionless. The patience for slow onboarding, hidden fees and poor UX has collapsed.",
    opportunities: [
      { title: "No freelancer-first challenger",       description: "1.2M ZZP in NL with no dedicated banking champion. Bunq goes broad, Revolut targets travellers." },
      { title: "Lack of Dutch-first communication",    description: "Most challengers run English-language ads. Dutch creative outperforms by 23% on recall (Nielsen 2024)." },
      { title: "Trust gap at bottom of funnel",        description: "Competitors focus on acquisition; few invest in safety and deposit guarantee reassurance content." },
    ],
    why_now: [
      "Switching intent increasing sharply after wave of fee hikes across big-4 banks",
      "Digital-only banking fully normalised post-COVID across all age groups",
      "Traditional bank trust at multi-year low — NPS gap widening",
      "Regulatory climate favours new entrants (PSD2, open banking)",
      "Open banking APIs dramatically reduce the friction of switching",
    ],
    strategic_implications: [
      "Lead with savings + UX as the primary message — this is what drives switching intent",
      "Build trust-heavy conversion flows with DNB licence and deposit guarantee prominently featured",
      "Prioritise Dutch-language creatives across all paid media channels",
      "Target freelancers as the primary high-value segment with dedicated messaging",
    ],
    risks: [
      "High CAC in fintech",
      "Trust barriers to switching",
      "Fast competitive replication",
      "Regulatory changes",
      "Low switching completion rate",
    ],
    positioning_space: "Zero-fee, full-control digital banking for Dutch urban professionals — combining modern UX with local trust and transparency. No competitor currently owns this space in Dutch-language creative.",
  }),

  audience: JSON.stringify({
    total: {
      name: "Total Audience",
      age_range: "25–38",
      jobs: "Knowledge workers, freelancers, young professionals",
      income: "€35–70K/year",
      daily_media_hours: "4.8 hours",
      size_estimate: "~280,000",
      motivations: [
        "Lower fees and transparent pricing",
        "Full control via mobile app",
        "Instant payment notifications",
        "Better spending insights",
      ],
      pain_points: [
        "Paying monthly fees for basic services",
        "App crashes during iDEAL payments",
        "Legacy banks lack modern UX",
        "No actionable spending insights",
      ],
      platforms: ["Instagram", "YouTube", "Spotify", "Google Search", "LinkedIn"],
    },
    personas: [
      {
        name: "Daan",
        age: "28",
        job: "UX Designer at a scale-up",
        income: "€52K/year gross",
        daily_media_hours: "5.2 hours",
        mindset: "Digital-first, convenience-driven, low loyalty to traditional banks. Expects bank apps to feel like consumer tech.",
        motivations: [
          "Save €90+/year on unnecessary fees",
          "Clean, intuitive app UX",
          "Instant spending notifications",
          "Smart budgeting categories",
        ],
        pain_points: [
          "Pays €8/month at ING for a basic account",
          "App crashes during iDEAL payments",
          "No spending insights or categorisation",
        ],
        trigger_moments: [
          "ING increases fees again",
          "Payment app crashes in a busy moment",
          "Friend shows him Vault — opens account in 5 min",
          "Wants to start a savings pot for a holiday",
        ],
        platforms: ["Instagram", "YouTube", "Spotify"],
        trust_builders: [
          "DNB licence prominently displayed",
          "Deposit guarantee (€100K)",
          "Reviews and social proof",
          "Easy onboarding demo",
        ],
        recommended: true,
      },
      {
        name: "Sven",
        age: "33",
        job: "Freelance developer (ZZP)",
        income: "€72K/year (variable)",
        daily_media_hours: "4.1 hours",
        mindset: "Financially self-sufficient, values control and flexibility. Frustrated by banks that don't understand freelancers.",
        motivations: [
          "Separate business and personal finances easily",
          "No unnecessary charges on variable income months",
          "Instant payment confirmation for client invoices",
        ],
        pain_points: [
          "Banks charge extra for business features he barely needs",
          "Hard to see cash flow at a glance",
          "Customer support is slow when something goes wrong",
        ],
        trigger_moments: [
          "Large invoice takes 3 days to clear",
          "Bank refuses to give him a second account",
          "Accountant recommends a smarter banking solution",
        ],
        platforms: ["LinkedIn", "YouTube", "Reddit"],
        trust_builders: [
          "Clear fee schedule — no surprises",
          "Fast customer support (chat, <5 min)",
          "DNB licensed and regulated",
        ],
      },
      {
        name: "Lisa",
        age: "26",
        job: "Marketing Manager, recently relocated to Amsterdam",
        income: "€42K/year gross",
        daily_media_hours: "5.8 hours",
        mindset: "Socially influenced, values aesthetics and peer validation. Discovery via social media. Switchers quickly if experience disappoints.",
        motivations: [
          "Bank that matches her digital lifestyle",
          "Looks and feels premium — card design matters",
          "Easy to split bills with friends",
          "Cashback or rewards",
        ],
        pain_points: [
          "Transferring money internationally is expensive",
          "Old bank app feels dated and clunky",
          "No card controls — can't freeze/unfreeze instantly",
        ],
        trigger_moments: [
          "Sees Vault card on Instagram",
          "Friend uses Vault to split dinner instantly",
          "Struggles with international transfer fees",
        ],
        platforms: ["Instagram", "TikTok", "Spotify", "Pinterest"],
        trust_builders: [
          "Social proof — friends already use it",
          "Beautiful card design",
          "Instant freeze/unfreeze via app",
        ],
      },
    ],
    barriers: [
      { barrier: "Switching banks feels like too much work", solution: "Emphasise 5-minute onboarding and automatic payment redirection" },
      { barrier: "Is a new bank actually safe?", solution: "Lead with DNB licence and €100K deposit guarantee" },
      { barrier: "I don't want to lose access to my old account", solution: "Promote dual-account approach — keep old bank, add Vault" },
    ],
  }),


  strategy: JSON.stringify({
    strategic_idea: "Build trust first, then convert on convenience and savings — using Dutch-language emotional storytelling to create mental availability before driving rational comparison.",
    audience_priority: [
      { segment: "Urban professionals", why: "Largest growth potential, highest fee frustration, most likely to switch", priority: "Primary" },
      { segment: "Freelancers / ZZP",   why: "Strongest positioning gap in market, high lifetime value, underserved", priority: "Primary" },
      { segment: "Students / starters", why: "Scalable low CPA segment, long lifetime value — build loyalty early", priority: "Secondary" },
    ],
    messaging_pillars: [
      { title: "Save money without compromise", description: "Zero fees, full control — no hidden costs, ever" },
      { title: "Banking built for modern life",  description: "App UX that works like your favourite consumer tech" },
      { title: "Dutch trust, digital convenience", description: "DNB licensed, local language, local culture" },
    ],
    stages: [
      { name: "Awareness", goal: "Build mental availability and brand trust", channels: ["YouTube Pre-roll", "Meta Video", "Spotify Audio"], kpi: "Impressions / Aided Awareness", target: "42M impressions · 40% aided awareness", message_type: "Banking that actually works for you — Dutch-language emotional storytelling", budget_pct: 40, conversion_rate: "4.2% click-through to consideration" },
      { name: "Consideration", goal: "Drive active product comparison and app visits", channels: ["Google Search", "Meta Carousel", "LinkedIn"], kpi: "Website visits / App store page views", target: "180,000 website visits · 95,000 app views", message_type: "Fee savings calculator · feature checklist · comparison", budget_pct: 30, conversion_rate: "28% conversion from visit to download" },
      { name: "Conversion", goal: "Drive account sign-ups at ≤ €45 CPA", channels: ["Google Search brand", "Meta Retargeting", "App Store Ads"], kpi: "Account openings / CPA", target: "44,000 accounts · CPA ≤ €45", message_type: "Social proof · urgency · 5-min onboarding demo", budget_pct: 22, conversion_rate: "46% complete onboarding after download" },
      { name: "Retention", goal: "Activate accounts and build habit behaviour", channels: ["Push notifications", "Email", "In-app messages"], kpi: "Activation rate / 30-day retention", target: "75% activation · 60% 30-day retention", message_type: "Onboarding tips · first transaction incentive · cashback offer", budget_pct: 8, conversion_rate: "" },
    ],
    channel_roles: [
      { channel: "YouTube",      role: "Awareness",    why: "Emotional reach — brand storytelling at scale to 25–38 urban professionals" },
      { channel: "Meta Social",  role: "Consideration", why: "Precise targeting + retargeting — reaches the right person at the right moment" },
      { channel: "Google Search", role: "Conversion",  why: "Intent capture — intercepts active switching intent at lowest CPA" },
      { channel: "Spotify",      role: "Awareness",    why: "Frequency builder — commute and gym moments, audio + visual combo" },
      { channel: "LinkedIn",     role: "Credibility",  why: "Professional credibility — targets freelancers and scale-up professionals" },
    ],
    retargeting_rules: [
      { trigger: "Visited website but did not download app", action: "Comparison ads · fee savings calculator · 7-day window" },
      { trigger: "Downloaded app but did not complete sign-up", action: "Push notification series · Meta retargeting · 3-day window" },
      { trigger: "Signed up but no first transaction within 7 days", action: "Email + in-app nudge · €5 cashback offer" },
    ],
    retargeting: [
      "Website visitors who did not download the app → Meta + Google Display with fee-saving message (7-day window)",
      "App downloaders who did not complete sign-up → Push notification series + Meta retargeting (3-day window)",
      "Completed sign-up but no first transaction → Email + in-app nudge with €5 cashback offer (7-day window)",
    ],
    channels: [
      { name: "YouTube Pre-roll",     role: "awareness",     motivation: "Highest video reach among 25–38 urban professionals.", targeting: "25–38, AMS/RTD/UTR, interest: fintech", formats: ["Non-skippable 15s", "Bumper 6s"], always_on: false, reach_index: 88, selectivity_index: 60, score_label: "●●●●○" },
      { name: "Meta Social",          role: "consideration", motivation: "Unmatched targeting precision and retargeting capabilities.", targeting: "25–38, 3 cities, lookalike + interest", formats: ["Reels 15s", "Stories", "Feed carousel"], always_on: true, reach_index: 85, selectivity_index: 78, score_label: "●●●●●" },
      { name: "Google Search",        role: "conversion",    motivation: "Captures high-intent users at lowest CPA in the mix.", targeting: "Keywords: gratis bankrekening, beste challenger bank", formats: ["Responsive Search Ads"], always_on: true, reach_index: 52, selectivity_index: 94, score_label: "●●●●●" },
      { name: "Spotify Audio",        role: "awareness",     motivation: "Reaches the audience during commute and gym — audio + display combo drives 18% higher recall.", targeting: "25–35, urban, commute/workout playlists", formats: ["Audio 30s + companion banner"], always_on: false, reach_index: 62, selectivity_index: 55, score_label: "●●●○○" },
      { name: "LinkedIn",             role: "retention",     motivation: "Targets the freelancer/ZZP segment with precision.", targeting: "Freelancers, self-employed, 26–40, NL", formats: ["Sponsored content", "InMail"], always_on: false, reach_index: 40, selectivity_index: 88, score_label: "●●●○○" },
      { name: "Push / Email / In-app", role: "retention",   motivation: "Activates registered users and builds transaction habit.", targeting: "Registered users, 0–30 days post sign-up", formats: ["Push", "Email", "In-app"], always_on: true, reach_index: 90, selectivity_index: 95, score_label: "●●●●●" },
    ],
    channel_overlap: [
      { channels: ["YouTube Pre-roll", "Meta Social", "Spotify Audio"], overlap_pct: 44, insight: "Align creative for consistent brand story across all awareness touchpoints." },
      { channels: ["Google Search", "Meta Social"],                      overlap_pct: 28, insight: "Low overlap — channels reach complementary consideration segments." },
      { channels: ["Google Search", "Meta Social"],                      overlap_pct: 62, insight: "High overlap intentional — reinforces purchase decision at the critical moment." },
      { channels: ["Push", "Email", "In-app"],                           overlap_pct: 85, insight: "Same user across all retention channels — coordinate timing to prevent fatigue." },
    ],
    synergy_score: 82,
    synergy_notes: "YouTube → Search shows 2.3× higher CTR for exposed users — branding directly feeds conversion performance.",
    budget_stages: [
      { stage: "Awareness",     amount: "€720K", pct: 40 },
      { stage: "Consideration", amount: "€540K", pct: 30 },
      { stage: "Conversion",    amount: "€396K", pct: 22 },
      { stage: "Retention",     amount: "€144K", pct: 8  },
    ],
    budget_rationale: "Higher awareness investment offsets trust barriers inherent in fintech adoption — brand-first spend accelerates downstream conversion efficiency.",
    north_star_kpi: "Cost per Acquisition ≤ €45",
    north_star_desc: "Blended across all channels over the full 10-week campaign window",
    success_metrics: [
      { label: "New accounts",          value: "44,000" },
      { label: "Aided awareness",       value: "40%" },
      { label: "App downloads",         value: "80,000" },
      { label: "30-day retention",      value: "60%" },
      { label: "Onboarding completion", value: "75%" },
      { label: "Awareness lift",        value: "+18pts" },
    ],
  }),

  competitive: JSON.stringify({
    competitors: [
      {
        name: "Bunq",
        est_budget: "€8-12M/year",
        positioning: "Sustainability-led challenger, feature-rich, premium pricing. Strong Dutch roots but broad European positioning.",
        channels: ["Instagram", "YouTube", "Display", "Search"],
        strengths: ["Strong Dutch brand recognition", "Feature-rich product", "Sustainability positioning"],
        weaknesses: ["Expensive relative to alternatives", "Feature overload for average user", "Complex onboarding"],
        sov_pct: 28,
        market_share_pct: 22,
        recent_ads: [
          { format: "YouTube 30s", platform: "YouTube", description: "Freelancer managing multiple income streams with zero stress", angle: "Freedom & independence" },
          { format: "Stories", platform: "Instagram", description: "Plant a tree with every payment — banking with purpose", angle: "Sustainability" },
        ],
      },
      {
        name: "Revolut",
        est_budget: "€15-20M/year",
        positioning: "Travel-first, low FX fees, aggressive acquisition. Global brand with limited local trust in NL.",
        channels: ["Search", "Meta", "OOH", "YouTube"],
        strengths: ["Lowest FX fees in market", "Strong app UX", "Large international user base"],
        weaknesses: ["Low local trust in NL", "English-only brand voice feels distant", "Customer service issues widely reported"],
        sov_pct: 35,
        market_share_pct: 18,
        recent_ads: [
          { format: "Search", platform: "Google", description: "Targeting: 'goedkope bankrekening', 'beste challenger bank NL'", angle: "Price comparison, acquisition-focused" },
          { format: "Video 15s", platform: "Instagram", description: "Pay like a local in 150+ countries — no hidden fees", angle: "Travel & low cost FX" },
        ],
      },
      {
        name: "N26",
        est_budget: "€3-5M/year",
        positioning: "Minimalist UX, German-origin. Limited Dutch-language presence and low local brand awareness.",
        channels: ["Meta", "Search", "Display"],
        strengths: ["Clean, minimal UX", "Strong brand in Germany", "Decent international reach"],
        weaknesses: ["Weak Dutch market presence", "No Dutch-language creative", "Limited brand awareness in NL"],
        sov_pct: 15,
        market_share_pct: 12,
        recent_ads: [
          { format: "Display", platform: "Programmatic", description: "Banking, simplified — open your account in 8 minutes", angle: "Speed & simplicity" },
        ],
      },
      {
        name: "ING / Rabobank",
        est_budget: "€40-60M/year",
        positioning: "Dominant incumbents. High trust, established relationships, poor digital UX and rising fees.",
        channels: ["TV", "OOH", "Radio", "Search", "Display"],
        strengths: ["Highest trust scores in market", "Established customer relationships", "Full product suite"],
        weaknesses: ["Poor UX perception vs challengers", "Rising fees alienating target audience", "Slow innovation cycle"],
        sov_pct: 22,
        market_share_pct: 48,
        recent_ads: [
          { format: "TV 30s", platform: "TV", description: "Together we make the Netherlands better — heritage and community", angle: "Trust & heritage" },
        ],
      },
    ],
    sov: [
      { brand: "Revolut",      pct: 35 },
      { brand: "Bunq",         pct: 28 },
      { brand: "ING / Rabo",   pct: 22 },
      { brand: "N26",          pct: 15 },
    ],
    sov_insight: "Revolut over-indexes in media spend relative to market share — signalling aggressive acquisition strategy targeting growth at all costs.",
    market_share: [
      { brand: "ING / Rabo",   pct: 48 },
      { brand: "Bunq",         pct: 22 },
      { brand: "Revolut",      pct: 18 },
      { brand: "N26",          pct: 12 },
    ],
    market_share_insight: "Incumbents hold nearly half the market but under-index on SOV — indicating low acquisition intent and reliance on existing customer inertia.",
    positioning_map: [
      { name: "Bunq",        x: 72, y: 78, color: "#1A0050" },
      { name: "Revolut",     x: 88, y: 60, color: "#5B21B6" },
      { name: "N26",         x: 68, y: 52, color: "#7C3AED" },
      { name: "ING / Rabo",  x: 22, y: 65, color: "#C4B5FD" },
      { name: "Vault",       x: 76, y: 42, color: "#5B21B6" },
    ],
    positioning_insight: "The innovative-accessible quadrant is contested but not owned. Vault can claim this space by combining modern UX with zero fees and Dutch-local trust — a combination no current player offers.",
    creative_patterns: [
      { icon: "📈", label: "Challengers: features & acquisition" },
      { icon: "🛡️", label: "Incumbents: trust & heritage" },
      { icon: "🇳🇱", label: "Dutch-local creative: underused" },
      { icon: "💜", label: "UX + reassurance combo: nobody" },
    ],
    weaknesses: [
      { name: "Bunq",       weakness: "Expensive and feature overloaded — perceived as complex and not worth the premium for average users" },
      { name: "Revolut",    weakness: "Low local trust in NL, customer service issues, English-only brand voice feels distant" },
      { name: "N26",        weakness: "Weak Dutch market presence, limited brand awareness, no Dutch-language creative strategy" },
      { name: "ING / Rabo", weakness: "Poor UX perception, legacy tech, increasing fees alienating exactly the audience Vault targets" },
    ],
    market_gaps: [
      { title: "No freelancer-first challenger",    description: "1.2M ZZP in NL with no dedicated banking champion" },
      { title: "Dutch-first comms missing",         description: "All challengers run English creative — 23% recall gap vs Dutch" },
      { title: "Trust gap at conversion",           description: "Challengers skip safety reassurance in bottom-funnel content" },
    ],
    white_space_title: "A Dutch-first digital bank that no current competitor owns:",
    white_space: [
      { label: "Modern UX — feels like consumer tech, not a bank" },
      { label: "Zero / low fees — no surprises, no monthly costs" },
      { label: "Freelancer relevance — built for the ZZP economy" },
      { label: "Dutch-local trust — DNB licence, local language, local culture" },
    ],
  }),

  funnel: JSON.stringify({
    stages: [
      {
        name: "Awareness",
        goal: "Reach 70% of target audience at least 3 times",
        channels: ["YouTube Pre-roll", "Meta Video", "Spotify Audio", "Programmatic Display"],
        kpi: "Impressions / Aided Awareness",
        target: "42M impressions · 40% awareness",
        message_type: "Emotional brand story — 'Banking that actually works for you'",
        budget_pct: 40,
        conversion_rate: "4.2% click-through to consideration",
      },
      {
        name: "Consideration",
        goal: "Drive active product comparison and app store visits",
        channels: ["Google Search", "Meta Carousel", "YouTube TrueView", "Reddit"],
        kpi: "Website visits / App store page views",
        target: "180,000 website visits · 95,000 app page views",
        message_type: "Rational comparison — fee savings calculator, feature checklist",
        budget_pct: 30,
        conversion_rate: "28% conversion from visit to app download",
      },
      {
        name: "Conversion",
        goal: "Drive account sign-ups at ≤ €45 CPA",
        channels: ["Google Search (brand)", "Meta Retargeting", "App Store Ads"],
        kpi: "Account openings / CPA",
        target: "44,000 accounts · CPA ≤ €45",
        message_type: "Urgency + social proof — 'Join 44,000 people who switched this month'",
        budget_pct: 22,
        conversion_rate: "46% complete onboarding after download",
      },
      {
        name: "Retention",
        goal: "Activate accounts and drive first transaction within 7 days",
        channels: ["Push notifications", "Email", "In-app messages"],
        kpi: "Activation rate / 30-day retention",
        target: "75% activation · 60% 30-day retention",
        message_type: "Onboarding tips + first transaction incentive (€5 cashback)",
        budget_pct: 8,
        conversion_rate: "",
      },
    ],
    retargeting: [
      "Website visitors who did not download the app → Meta + Google Display with fee-saving message (7-day window)",
      "App downloaders who did not complete sign-up → Push notification series + Meta retargeting (3-day window)",
      "Completed sign-up but no first transaction → Email + in-app nudge with €5 cashback offer (7-day window)",
    ],
    budget_split: [
      { stage: "Awareness", pct: 40 },
      { stage: "Consideration", pct: 30 },
      { stage: "Conversion", pct: 22 },
      { stage: "Retention", pct: 8 },
    ],
  }),

  channel: JSON.stringify({
    channels: [
      { name: "YouTube Pre-roll", role: "awareness", motivation: "Highest video reach among 25–38 urban professionals. Non-skippable 15s builds rapid brand familiarity at competitive CPM.", targeting: "25–38, Amsterdam/Rotterdam/Utrecht, interest: fintech, personal finance, design", formats: ["Non-skippable 15s", "Bumper 6s"], always_on: false, reach_index: 88, selectivity_index: 60, score_label: "●●●●○" },
      { name: "Meta Social", role: "awareness", motivation: "Unmatched targeting precision for urban professionals. Instagram Stories and Reels drive strong brand recall and click-through.", targeting: "25–38, 3 cities, behaviours: mobile banking app users, lookalike of current customer base", formats: ["Reels 15s", "Stories", "Feed carousel"], always_on: true, reach_index: 85, selectivity_index: 78, score_label: "●●●●●" },
      { name: "Google Search", role: "conversion", motivation: "Captures high-intent users actively searching for banking alternatives. Brand + competitor keywords drive lowest CPA in the mix.", targeting: "Keywords: gratis bankrekening, beste challenger bank, Bunq alternatief, Vault bank", formats: ["Responsive Search Ads", "Brand keywords"], always_on: true, reach_index: 52, selectivity_index: 94, score_label: "●●●●●" },
      { name: "Programmatic Display", role: "consideration", motivation: "Cost-efficient retargeting layer. Keeps Vault top-of-mind for users who engaged with video but haven't converted.", targeting: "Retargeting: video viewers + website visitors (30-day window). Contextual: personal finance content", formats: ["300x250", "728x90", "Native"], always_on: false, reach_index: 70, selectivity_index: 65, score_label: "●●●●○" },
      { name: "Spotify Audio", role: "awareness", motivation: "Reaches the audience during commute and gym — key moments when they're not scrolling. Audio + display combo drives 18% higher recall.", targeting: "25–35, urban, playlists: workout, commute, focus work", formats: ["Audio 30s + companion banner"], always_on: false, reach_index: 62, selectivity_index: 55, score_label: "●●●○○" },
      { name: "LinkedIn", role: "consideration", motivation: "Targets the freelancer/ZZP segment with precision. Sponsored InMail for freelancer-specific messaging about expense management.", targeting: "Freelancers, self-employed, 26–40, NL, job function: creative, consulting, tech", formats: ["Sponsored content", "InMail"], always_on: false, reach_index: 40, selectivity_index: 88, score_label: "●●●○○" },
    ],
    channel_overlap: [
      { channels: ["YouTube", "Meta"], overlap_pct: 44, insight: "44% of the target audience is reachable on both platforms. Coordinate creative to build a coherent brand story across both touchpoints." },
      { channels: ["YouTube", "Meta", "Search"], overlap_pct: 31, insight: "31% see all three — these are your highest-intent prospects. Ensure message progression from awareness → consideration → conversion." },
    ],
    attribution_model: "Data-driven attribution (Google) + Meta 7-day click / 1-day view",
    frequency_cap: "YouTube: 3x/week · Meta: 4x/week · Display: 5x/week",
    synergy_score: 82,
    synergy_notes: "Strong synergy between YouTube brand building and Google Search conversion. Users exposed to YouTube pre-roll show 2.3x higher Search CTR (Nielsen study, comparable fintech launch 2024).",
  }),

  budget: JSON.stringify({
    total_budget: 2000000,
    net_budget:   1800000,
    by_funnel: [
      { stage: "Awareness",     budget: 720000, pct: 40 },
      { stage: "Consideration", budget: 540000, pct: 30 },
      { stage: "Conversion",    budget: 396000, pct: 22 },
      { stage: "Retention",     budget: 144000, pct: 8  },
    ],
    budget_rationale: [
      "Higher awareness investment offsets trust barriers inherent in fintech adoption",
      "Conversion budget prioritises high-intent channels with proven CPA performance",
      "Retention investment focuses on activation efficiency, not paid acquisition",
    ],
    by_channel: [
      { channel: "Meta Social",   budget: 504000, pct: 28 },
      { channel: "YouTube",       budget: 396000, pct: 22 },
      { channel: "Google Search", budget: 360000, pct: 20 },
      { channel: "Programmatic",  budget: 270000, pct: 15 },
      { channel: "Spotify",       budget: 180000, pct: 10 },
      { channel: "LinkedIn",      budget:  90000, pct: 5  },
    ],
    test_budget: {
      amount: 180000,
      pct: 10,
      tests: ["Dutch vs English creative", "Savings-led vs trust-led messaging", "Freelancer targeting vs broad 25-38", "Short-form vs long-form video"],
      refresh_week: 5,
    },
    pacing: {
      strategy: "Burst + Always-on",
      motivation: "Heavy burst to build rapid mental availability, then transition to efficient always-on performance from week 4.",
      phases: [
        { label: "Burst",        weeks: "Weeks 1–3", description: "Heavy awareness burst — YouTube + Meta Video + Spotify at maximum frequency to establish mental availability", color: "#1A0050" },
        { label: "Peak",         weeks: "Weeks 4–6", description: "Shift to peak performance — consideration and conversion channels activate, retargeting pools now large enough to optimise", color: "#5B21B6" },
        { label: "Always-on",    weeks: "Weeks 7–10", description: "Always-on performance and retention focus — brand spend reduces, Search and retargeting carry conversion load efficiently", color: "#7C3AED" },
      ],
      weeks: [
        { week: 1,  budget: 280000, phase: "Burst",    focus: "Maximum YouTube + Meta awareness — launch hero Dutch creative" },
        { week: 2,  budget: 265000, phase: "Burst",    focus: "Sustain awareness burst, begin building retargeting pools" },
        { week: 3,  budget: 240000, phase: "Burst",    focus: "Final burst week — Spotify audio activates, frequency cap review" },
        { week: 4,  budget: 195000, phase: "Peak",     focus: "Activate Google Search brand + consideration Meta Carousel" },
        { week: 5,  budget: 185000, phase: "Peak",     focus: "Creative refresh based on test results — optimise top performers" },
        { week: 6,  budget: 170000, phase: "Peak",     focus: "Push retargeting hard — app downloaders targeted with onboarding ads" },
        { week: 7,  budget: 135000, phase: "Always-on", focus: "Scale back brand spend, Search + retargeting carry load" },
        { week: 8,  budget: 125000, phase: "Always-on", focus: "Activate retention campaigns for early account holders" },
        { week: 9,  budget: 115000, phase: "Always-on", focus: "Referral programme launch — organic amplification begins" },
        { week: 10, budget: 110000, phase: "Always-on", focus: "Final push — CPA optimisation, account activation incentives" },
      ],
    },
    optimisation_rules: [
      { icon: "📊", title: "Weekly budget reallocation",   desc: "Shift spend toward channels outperforming CPA targets — reviewed every Monday with 48h implementation window" },
      { icon: "⏱️", title: "Creative fatigue management",  desc: "Pause creatives below CTR benchmark after 7 days — rotate at least 3 variants per channel per phase" },
      { icon: "🔍", title: "Search signal trigger",         desc: "Increase retargeting spend automatically when branded search volume rises 20%+ above baseline" },
      { icon: "🎯", title: "CPA guardrails",               desc: "If blended CPA exceeds €55 for 5 consecutive days, pause lowest-performing channel and shift budget to Search" },
    ],
    test_items: [
      { title: "Creative language",   option_a: "Dutch",          option_b: "English" },
      { title: "Messaging angle",     option_a: "Savings-led",    option_b: "Trust-led" },
      { title: "Audience targeting",  option_a: "Freelancer",     option_b: "Broad 25–38" },
      { title: "Video format",        option_a: "Short-form 15s", option_b: "Long-form 30s" },
    ],
  }),

  mediaplan: JSON.stringify({
    totals: {
      budget:      1800000,
      impressions: 79100000,
      clicks:      1847000,
      conversions: 43616,
      blended_cpa: 41.27,
    },
    channels: [
      {
        name:         "Meta Social",
        funnel_stage: "Awareness",
        platform:     "Meta",
        buy_type:     "Auction CPM",
        targeting:    "25–38, Amsterdam/Rotterdam/Utrecht, lookalike + interest: fintech · Freq cap 4×/week",
        formats:      ["Reels 15s", "Stories", "Feed Carousel"],
        budget:       504000,
        impressions:  28000000,
        cpm:          18.00,
        clicks:       840000,
        ctr:          3.0,
        conversions:  18144,
        cpa:          27.78,
      },
      {
        name:         "YouTube Pre-roll",
        funnel_stage: "Awareness",
        platform:     "YouTube",
        buy_type:     "CPV",
        targeting:    "25–38, urban NL, interest: fintech, personal finance · Freq 3×/week",
        formats:      ["Non-skip 15s", "Bumper 6s"],
        budget:       396000,
        impressions:  21290000,
        cpm:          18.60,
        clicks:       425800,
        ctr:          2.0,
        conversions:  9920,
        cpa:          58.06,
      },
      {
        name:         "Google Search",
        funnel_stage: "Conversion",
        platform:     "Google",
        buy_type:     "CPC tCPA",
        targeting:    "gratis bankrekening, beste challenger bank, Vault bank · Smart bidding tCPA €40",
        formats:      ["Responsive Search Ads", "Brand"],
        budget:       360000,
        impressions:  3600000,
        cpm:          1.25,
        clicks:       288000,
        ctr:          8.0,
        conversions:  12960,
        cpa:          27.78,
      },
      {
        name:         "Programmatic Display",
        funnel_stage: "Consideration",
        platform:     "DV360",
        buy_type:     "CPM",
        targeting:    "Retargeting: video viewers + website visitors (30-day window)",
        formats:      ["300×250", "728×90", "Native"],
        budget:       270000,
        impressions:  64285714,
        cpm:          4.20,
        clicks:       225000,
        ctr:          0.35,
        conversions:  2592,
        cpa:          104.17,
      },
    ],
    execution_insights: [
      { icon: "🎯", title: "Meta drives most efficient scalable acquisition",        desc: "Lowest blended CPA (€27.78) at meaningful volume — primary performance engine throughout campaign" },
      { icon: "🔍", title: "Google Search captures highest-intent demand",            desc: "8% CTR confirms strong keyword relevance — tCPA bidding optimising toward €40 target" },
      { icon: "📺", title: "YouTube delivers broad reach, lower direct efficiency",  desc: "€58 CPA acceptable given brand-building value — feeds Search and Meta downstream via audience exposure" },
      { icon: "📊", title: "Programmatic supports retargeting at low CPM",          desc: "€4.20 CPM makes it cost-efficient for top-of-funnel recency targeting — not a conversion channel" },
    ],
    optimisation_notes: [
      "Weekly budget reallocation based on CPA performance — channels outperforming targets receive increased allocation each Monday",
      "Creative refresh every 2 weeks — minimum 3 variants per channel to combat fatigue and maintain CTR benchmarks",
      "Retargeting intensity increases progressively over campaign duration as audience pools from awareness channels grow",
      "Branded search spend scales up when awareness metrics confirm mental availability is building (aided awareness >25%)",
      "Programmatic paused if CPA exceeds €120 for 5 consecutive days — budget redirected to Meta retargeting",
    ],
  }),

  synthesis: JSON.stringify({
    campaign_name: "Vault · Q1 2026 Media Strategy",
    summary_paragraphs: [
      "Vault enters the Dutch digital banking market with a trust-first, Dutch-language media strategy targeting urban professionals and freelancers aged 25–38. By combining emotional brand storytelling with rational performance conversion, the campaign builds mental availability before driving account sign-ups at scale.",
      "The strategy exploits a clear competitive white space: no challenger currently owns the Dutch-local, zero-fee, modern-UX positioning in Dutch-language creative. With €2M over 10 weeks, Vault can build 40% aided awareness while driving 44,000 account openings at a blended CPA of €41 — within target.",
      "Success depends on creative quality, Dutch-language execution, and a disciplined burst-to-always-on pacing model that builds brand equity in weeks 1–3 before converting that attention into accounts in weeks 4–10.",
    ],
    summary: "Vault enters the Dutch digital banking market with a trust-first strategy targeting urban professionals aged 25–38. With €2M over 10 weeks, the campaign builds 40% aided awareness while driving 44,000 account openings at a blended CPA of €41.",
    strategic_core: [
      { title: "Own Dutch trust + digital convenience", description: "No competitor combines local language, DNB trust signals and modern UX — this is Vault\'s unclaimed territory" },
      { title: "Awareness-led growth overcomes trust barriers", description: "40% of budget in awareness is justified — fintech adoption requires brand familiarity before rational comparison works" },
      { title: "Meta + Search form the primary acquisition engine", description: "Both channels deliver ≤€28 CPA — together they drive 72% of total conversions at the most efficient cost" },
    ],
    outcomes: [
      { label: "New accounts",      value: "44,000",  sub: "CPA ≤ €45 target" },
      { label: "Blended CPA",       value: "€41",     sub: "Within €45 target" },
      { label: "Aided awareness",   value: "40%",     sub: "+18pts lift vs baseline" },
      { label: "App downloads",     value: "80,000",  sub: "46% onboarding completion" },
      { label: "30-day retention",  value: "60%",     sub: "75% activation rate" },
      { label: "Total impressions", value: "79M",     sub: "Across all channels" },
    ],
    risks: [
      { level: "high",   risk: "Bunq or Revolut launch a counter-spend campaign during burst phase",              mitigation: "Keep €100K contingency budget ready to defend SOV" },
      { level: "high",   risk: "Burst phase temporarily inflates blended CPA above €45",                          mitigation: "Measure CPA as 10-week blended average, not week-by-week" },
      { level: "medium", risk: "Trust barrier remains high — brand recall does not convert to sign-ups at expected rate", mitigation: "Strengthen bottom-funnel DNB + deposit guarantee messaging" },
      { level: "medium", risk: "Creative performance varies significantly across personas and formats",             mitigation: "Test agenda activated from week 1 — refresh at week 5" },
    ],
    recommendations: [
      { title: "Produce Dutch-language creative from day one", priority: "high",   description: "Dutch ads outperform English by 23% on recall — all hero assets must be Dutch from launch" },
      { title: "Launch referral programme at week 6",          priority: "high",   description: "At ~20K accounts, referral drives organic growth at €20 CPA — well below paid channels" },
      { title: "Add savings calculator to landing page",       priority: "medium", description: "Converts fee frustration into tangible switching motivation — primary consideration asset" },
      { title: "Optimise onboarding flow before burst",        priority: "medium", description: "Every 1% improvement in completion rate = ~440 additional accounts at zero extra media cost" },
    ],
    next_steps: [
      { action: "Brief creative agency on Dutch-language hero film",         owner: "Marketing",    timing: "Week −4" },
      { action: "Finalise media plan and book inventory (YouTube, Spotify)",  owner: "Media agency", timing: "Week −3" },
      { action: "Build savings calculator and optimise landing page",         owner: "Product",      timing: "Week −2" },
      { action: "Set up tracking, attribution and weekly reporting dashboard", owner: "Data",         timing: "Week −1" },
      { action: "Launch burst — activate all awareness channels simultaneously", owner: "Media agency", timing: "Week 1" },
      { action: "Launch referral programme and activate retention campaigns", owner: "Marketing",    timing: "Week 6" },
    ],
  }),

};
